version: '{build}'
image: Visual Studio 2015
configuration: Release
pull_requests:
  do_not_increment_build_number: true

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: hws7DJdLNszyiV5mPr+BiotrEmanc6ipoIUUC0Xb8XOrEHItGfd+4v0+PnIJHPP6

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -pre -y

assembly_info:
  patch: true

before_build:
  - nuget restore src/Serilog.Enrichers.HttpContextInfo.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value

build:
  project: src/Serilog.Enrichers.HttpContextInfo.sln

after_build:
  - cmd: nuget pack src\Serilog.Enrichers.HttpContextInfo\Serilog.Enrichers.HttpContextInfo.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

after_test:
  -cmd: src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"src\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single src\Serilog.Enrichers.HttpContextInfo.Tests\bin\$env:CONFIGURATION\Serilog.Enrichers.HttpContextInfo.Tests.dll" -output:coverage.xml

artifacts:
  - path: '*.nupkg'
    name: NuGet

deploy:
  - provider: Environment
    name: PreRelease NuGet Feed
    on:
      branch: master
  - provider: Environment
    name: Public NuGet Feed
    on:
      appveyor_repo_tag: true
